services:
  postgres:
    image: postgres:latest
    container_name: postgres_subscriptions
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres_user -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true
    expose:
      - 5432

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.3
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://postgres_user:postgres_password@postgres:5432/postgres_db
      - GOOSE_COMMAND=up

    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres

  api:
    build: .
    container_name: subscriptions_api
    
    ports:
    - 8080:8080
    environment:
     DB_HOST: ${DB_HOST}
     DB_NAME: ${DB_NAME}
     DB_PASSWORD: ${DB_PASSWORD}
     DB_USER: ${DB_USER}
     DB_PORT: ${DB_PORT}
    depends_on:
      - postgres

volumes:
  pgdata:
    driver: local